services:
  # django-project-db:
  #   image: postgres:16.6
  #   container_name: django-project-postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: django_project
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - django_project_db_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD", "pg_isready", "-U", "postgres", "-d", "django_project"]
  #     interval: 10s
  #     retries: 5
  #     start_period: 5s
  #     timeout: 5s
  #   networks:
  #     - django-project-network

  # django-project-redis:
  #   image: redis:7.2.5
  #   container_name: django-project-redis
  #   ports:
  #     - "6379:6379"
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 10s
  #     retries: 5
  #     start_period: 5s
  #     timeout: 5s
  #   networks:
  #     - django-project-network

  nginx:
    image: nginx:latest
    container_name: django-project-nginx
    depends_on:
      - django-project-1
      - django-project-2
      - django-project-3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - django-project-network

  django-project-1:
    container_name: django-project-1
    restart: on-failure:3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - .:/app
    # depends_on:
    #   - django-project-db
    #   - django-project-redis
    environment:
      - DATABASE_URL=postgres://postgres:password@django-project-db:5432/django_project?sslmode=disable
      - REDIS_URL=redis://django-project-redis:6379
    networks:
      - django-project-network

  django-project-2:
    container_name: django-project-2
    restart: on-failure:3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    volumes:
      - .:/app
    # depends_on:
    #   - django-project-db
    #   - django-project-redis
    environment:
      - DATABASE_URL=postgres://postgres:password@django-project-db:5432/django_project?sslmode=disable
      - REDIS_URL=redis://django-project-redis:6379
    networks:
      - django-project-network

  django-project-3:
    container_name: django-project-3
    restart: on-failure:3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    volumes:
      - .:/app
    # depends_on:
    #   - django-project-db
    #   - django-project-redis
    environment:
      - DATABASE_URL=postgres://postgres:password@django-project-db:5432/django_project?sslmode=disable
      - REDIS_URL=redis://django-project-redis:6379
    networks:
      - django-project-network

networks:
  django-project-network:
    driver: bridge

volumes:
  django_project_db_data:
