services:
  django-project:
    container_name: django-project
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/app # Mount the current directory to /app inside the container
    ports:
      - "8080:8080"
    networks:
      - django_project

networks:
  django_project:
    driver: bridge
